SportsStore/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private readonly Cart cart;

        public CartSummaryViewComponent(Cart cart)
        {
            this.cart = cart;
        }

        public IViewComponentResult Invoke()
        {
            return this.View(this.cart);
        }
    }
}

SportsStore/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models.Repository;

namespace SportsStore.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private readonly IStoreRepository repository;

        public NavigationMenuViewComponent(IStoreRepository repository)
        {
            this.repository = repository;
        }

        public IViewComponentResult Invoke()
        {
            this.ViewBag.SelectedCategory = this.RouteData?.Values["category"];

            return this.View(this.repository.Products
                 .Select(x => x.Category)
                 .Distinct()
                 .OrderBy(x => x));
        }
    }
}

SportsStore/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Infrastructure;
using SportsStore.Models;
using SportsStore.Models.Repository;
using SportsStore.Models.ViewModels;

namespace SportsStore.Controllers
{
    public class CartController : Controller
    {
        private IStoreRepository repository;

        public CartController(IStoreRepository repository, Cart cart)
        {
            this.repository = repository;
            this.Cart = cart;
        }

        public Cart Cart { get; set; }

        [HttpGet]
        public IActionResult Index(string returnUrl)
        {
            return View(new CartViewModel
            {
                ReturnUrl = returnUrl ?? "/",
                Cart = this.Cart
            });
        }

        [HttpPost]
        public IActionResult Index(long productId, string returnUrl)
        {
            Product? product = repository.Products.FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
            {
                this.Cart.AddItem(product, 1);

                return View(new CartViewModel
                {
                    Cart = this.Cart,
                    ReturnUrl = returnUrl
                });
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult Remove(long productId, string returnUrl)
        {
            Product? product = repository.Products.FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
            {
                this.Cart.RemoveLine(product);
            }

            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

SportsStore/Views/Shared/_CartLayout.cshtml
<!DOCTYPE html>
<html lang ="en" xml:lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SportsStore</title>
    <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-primary text-white p-2">
        <span class="navbar-brand ml-2">SPORTS STORE</span>
    </div>
    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>

SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" xml:lang="en">
<head >
    <meta name="viewport" content="width=device-width" />
    <title>SportsStore</title>
    <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
   <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
   <link href="/hover/HoverStyle.css" rel="stylesheet" />
    <script src="/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/font-awesome/js/ThemeChanger.js"> </script>
</head>
<body class="bg-dark text-light" style="background-color: #363C46 !important; color: #F8F0E5 !important;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3" style="color: #F8F0E5 !important;">
            <div class="container">
                <a class="navbar-brand" style="color: #F8F0E5!important" asp-area="" asp-controller="Home" asp-action="Index">Sport Store</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-center" style="color: #F8F0E5!important">
                    <ul class="navbar-nav flex-grow-1" >

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: #F8F0E5 !important;">
                                Products
                            </a>
                            <ul class="dropdown-menu p-2" style="background-color: #363C46 !important;">
                                <vc:navigation-menu />
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Account" asp-action="Login" style="color: #F8F0E5 !important;">Login</a>
                        </li>
                        <li class="nav-item navbar-text ms-auto text-end">
                            <vc:cart-summary />
                        </li>
                    </ul>
                </div>
            </div>
            <div class="form-check form-switch">
                <input class="form-check-input" type="checkbox" id="btnSwitch" role="switch">
                <label class="form-check-label bg-dark" for="flexSwitchCheckDefault"></label>
            </div>

        </nav>
    </header>
    <div class="container text-center w-100 flex-grow-1">
        @RenderBody()
    </div>
    <footer class="border-top footer text-muted " style="min-height:50px; position:sticky">
        <div class="container" style="color: #F8F0E5 !important;">
            &copy; 2024 - Sport Shop - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>
</body>
</html>

SportsStore/Views/Shared/_ProductSummary.cshtml
@model Product

<div class="card b-2  p-3 w-100 m-3 h-100" style="background-color: #363C46 !important; color: #F8F0E5 !important; border-color: #F8F0E5 !important;">
    <div class="row g-0 h-100" >
        <!-- Image Block -->
        <div class="col-12 col-md-4 text-center p-2 d-flex align-items-center justify-content-center ">
            <img src="@Model?.PictureUrl" alt="Product Image" class="img-fluid rounded"
                 style="max-height: 150px; object-fit: cover;">
        </div>

        <!-- Product Info Block -->
        <div class="col-12 col-md-5 text-start p-3 d-flex flex-column justify-content-between">
            <div>
                <h4>@Model?.Name</h4>
                <p class="text-muted" style=" color: #F8F0E5 !important;">@Model?.Description</p>
            </div>
        </div>

        <!-- Price and Button Block -->
        <div class="col-12 col-md-3 text-start p-3 d-flex flex-column justify-content-between" style=" color: #F8F0E5 !important;">
            <div>
                <span class="fw-bold">Price:</span>
                <span class="badge bg-primary text-white">@Model?.Price.ToString("c")</span>
            </div>
            <form id="@Model?.ProductId" asp-controller="Cart" asp-antiforgery="true" class="mt-auto">
                <input type="hidden" asp-for="ProductId" />
                <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                <button type="submit" class="btn btn-success btn-sm w-100">Add To Cart</button>
            </form>
        </div>
    </div>
</div>